package com.demo.error_handling_sp;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class GroupCoverage implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String prodStatus;
	private java.lang.String groupProduct;

	public GroupCoverage() {
	}

	public java.lang.String getProdStatus() {
		return this.prodStatus;
	}

	public void setProdStatus(java.lang.String prodStatus) {
		this.prodStatus = prodStatus;
	}

	public java.lang.String getGroupProduct() {
		return this.groupProduct;
	}

	public void setGroupProduct(java.lang.String groupProduct) {
		this.groupProduct = groupProduct;
	}

	public GroupCoverage(java.lang.String prodStatus,
			java.lang.String groupProduct) {
		this.prodStatus = prodStatus;
		this.groupProduct = groupProduct;
	}
	
	public String toString() {
	    return "GroupCoverage[prodStatus="+prodStatus+", groupProduct="+groupProduct+"]";
	}

}