package com.demo.error_handling_sp;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class GroupCoverage implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public GroupCoverage() {
    }




}